apiVersion: v1
kind: Service
metadata:
  name: finxplore-service
spec:
  type: NodePort # Exposes it to outside (for development)
  selector:
    app: finxplore-api
  ports:
    - name: http
      protocol: TCP
      port: 80        # Internal Cluster Port
      targetPort: 8080 # Container Port
      nodePort: 30000 # Access via localhost:30000 (if using Minikube/Docker Desktop)
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30051